M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Fri May 26 01:14:44 2023
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2023-05-26T01:14:44+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X-2710Y-6720
X3390Y-10620
X18040Y-15320
T2
X0Y0
X0Y-20320
X40640Y0
T0
M30
